name: Java CI with Maven

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

  Build-jar:
      uses: felipefernandes1324/Workflows/.github/workflows/BuildingJava17WithMaven.yml@main
      with:
        image_name: teste-pipeline
        tag: $GITHUB_RUN_NUMBER
        
